### PR TITLE
Fix for Issue #16

### PR DESCRIPTION
**Pull request by zpappa**
Fixes the downstream issue with linux systems passing IPV6 and IPV4 information to the connection obtained from net.createServer.

### CODE REVIEW

**Comment by elad** [comment]
I don't understand this change. You're always checking `ip[1]`. Is this intentional?

**Comment by carasel** [comment]
Should be checking `ip[i]`. I had the same issue on mac and used the same fix before seeing this.

**Comment by elad** [comment]
@carasel care to submit a fixed PR?

**Comment by elad** [comment]
Closing in favor of #21

**Pull request closed without merging**
